// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVa5dRtXraAMPnDS6t1-ZvnUnMaX6a3ZQ',
    appId: '1:663100452712:web:172320e390e798311870dd',
    messagingSenderId: '663100452712',
    projectId: 'fyp-safe-415110',
    authDomain: 'fyp-safe-415110.firebaseapp.com',
    databaseURL: 'https://fyp-safe-415110-default-rtdb.firebaseio.com',
    storageBucket: 'fyp-safe-415110.appspot.com',
    measurementId: 'G-RKK12P20PQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBII92b5wNn3xI177FCkJVRcdwj0_uxl6o',
    appId: '1:663100452712:android:0a6b26af995a14a51870dd',
    messagingSenderId: '663100452712',
    projectId: 'fyp-safe-415110',
    databaseURL: 'https://fyp-safe-415110-default-rtdb.firebaseio.com',
    storageBucket: 'fyp-safe-415110.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzQiBXZM42vqWilQ9WtLFaP9kD1SJMqrw',
    appId: '1:663100452712:ios:0e4e6611a0ce4e3c1870dd',
    messagingSenderId: '663100452712',
    projectId: 'fyp-safe-415110',
    databaseURL: 'https://fyp-safe-415110-default-rtdb.firebaseio.com',
    storageBucket: 'fyp-safe-415110.appspot.com',
    iosBundleId: 'com.example.fypSafe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDzQiBXZM42vqWilQ9WtLFaP9kD1SJMqrw',
    appId: '1:663100452712:ios:0e4e6611a0ce4e3c1870dd',
    messagingSenderId: '663100452712',
    projectId: 'fyp-safe-415110',
    databaseURL: 'https://fyp-safe-415110-default-rtdb.firebaseio.com',
    storageBucket: 'fyp-safe-415110.appspot.com',
    iosBundleId: 'com.example.fypSafe',
  );
}
